name: verify
on: [push]

jobs:
  cowsay:
    runs-on: ubuntu-latest
    container: npalm/cowsay

    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "TEST" > ~/test.txt
          cowsay -f ghostbusters "  `cat ~/test` "
